#!/bin/sh

sort $1 > tempxxxFile

for i in 12 11 10 09 08 07 06 05 04 03 02 01 
do
	timezone='-'"$i"'00'
	commitCount=$(grep -c -E '[0-9]{4} \-'"$i"'00$' tempxxxFile)
	if [ $commitCount != 0 ]
	then
		echo "$timezone $commitCount"
	fi
done

for i in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14
do
	timezone='+'"$i"'00'
	commitCount=$(grep -c -E '[0-9]{4} \+'"$i"'00'$ tempxxxFile)
	if [ $commitCount != 0 ]
	then
		echo "$timezone $commitCount"	
	fi
done
rm tempxxxFile
